REVO i.MX7D: Rearrange Smallstep scripts.

diff --git a/revo/resources/smallstep/enable-step-ca b/revo/resources/smallstep/enable-step-ca
--- a/revo/resources/smallstep/enable-step-ca
+++ b/revo/resources/smallstep/enable-step-ca
@@ -7,6 +7,9 @@
 # architectures, step-ca is initialized.
 #
 declare script_name=${0##*/}
+declare script_dir=$(readlink -e "$0")
+
+script_dir=${script_dir%/*}
 
 declare cli_uri=https://github.com/smallstep/cli
 declare certificates_uri=https://github.com/smallstep/certificates
@@ -53,7 +56,7 @@ where OPTIONS are:
              (default: ${argv[template]})
   -u|--user-name=NAME
              Set name of certificate authority owner.
-             (default: ${argv[groupname]})
+             (default: ${argv[username]})
 EOF
 }
 
@@ -219,7 +222,7 @@ After=syslog.target network.target
 Type=simple
 User=${argv[username]}
 Group=${argv[groupname]}
-ExecStart=/bin/bash -c "step-ca \$(step path)/config/ca.json --password-file=\$(step path)/secrets/${argv[password_file]} >>${argv[logdir]}/step-ca.log 2>&1"
+ExecStart=/bin/bash -c "$STEP_CA \$($STEP_CLI path)/config/ca.json --password-file=\$($STEP_CLI path)/secrets/${argv[password_file]} >>${argv[logdir]}/step-ca.log 2>&1"
 Restart=on-failure
 RestartSec=10
 
@@ -238,13 +241,15 @@ issue-link-local-certificate ()
     local -n argv=$1
 
     sudo -E -u ${argv[username]} provisioner=${argv[provisioner]} \
-         STEPPATH=$STEPPATH bash <<'EOF'
-    declare link_local=$(hostname -s).local
-    declare token=$(
-        step ca token "$link_local" --issuer "$provisioner" --password-file "$(step path)/secrets/provisioner.pwd"
-          )
-    eval cd ~$USER
-    step ca certificate "$link_local" "${link_local}.crt" "${link_local}.key" --token "$token"
+         STEPPATH=$STEPPATH STEP_CLI=$STEP_CLI bash <<'EOF'
+declare link_local=$(hostname -s).local
+declare token=$(
+    $STEP_CLI ca token "$link_local" --issuer "$provisioner" \\
+    --password-file "$(step path)/secrets/provisioner.pwd"
+      )
+eval cd ~$USER
+$STEP_CLI ca certificate "$link_local" "${link_local}.crt" \\
+    "${link_local}.key" --token "$token"
 EOF
 }
 
@@ -253,13 +258,15 @@ issue-fqdn-certificate ()
     local -n argv=$1
 
     set -x
-    sudo -E -u ${argv[username]} fqdn=${argv[fqdn]} provisioner=${argv[provisioner]} \
-         STEPPATH=$STEPPATH bash <<'EOF'
-    declare token=$(
-        step ca token "$fqdn" --issuer "$provisioner" --password-file "$(step path)/secrets/provisioner.pwd"
-          )
-    eval cd ~$USER
-    step ca certificate "$fqdn" "${fqdn}.crt" "${fqdn}.key" --token "$token"
+    sudo -E -u ${argv[username]} fqdn=${argv[fqdn]} \
+         provisioner=${argv[provisioner]} \
+         STEPPATH=$STEPPATH STEP_CLI=$STEP_CLI bash <<'EOF'
+declare token=$(
+    $STEP_CLI ca token "$fqdn" --issuer "$provisioner" \\
+    --password-file "$(step path)/secrets/provisioner.pwd"
+      )
+eval cd ~$USER
+$STEP_CLI ca certificate "$fqdn" "${fqdn}.crt" "${fqdn}.key" --token "$token"
 EOF
 }
 
@@ -351,6 +358,11 @@ if test ."$0" = ."${BASH_SOURCE[0]}"; then
         shift 2
     done
 
+    if test ! -f "${param[template]}"; then
+        sed -n '/BEGIN patch/,$s/^# //p' "${script_dir}/${script_name}" |
+            patch -p0
+    fi
+
     if test ! -x "$STEP_CLI"; then
         fetch-and-install-dpkg "$cli_uri"
     fi
@@ -370,3 +382,107 @@ if test ."$0" = ."${BASH_SOURCE[0]}"; then
 
     sudo systemctl status step-ca
 fi
+
+# **** BEGIN patch ****
+# --- init-step-ca.in	2021-03-15 19:13:22.050211428 -0400
+# +++ /dev/null	2021-03-13 15:12:11.186395129 -0500
+# @@ -0,0 +1,99 @@
+# +#!/usr/bin/env bash
+# +#
+# +# This script initializes the step CA.
+# +
+# +# Exit immediately on error.
+# +set -e
+# +
+# +# Return uniformly distributed random integer in the range [0,$bound).
+# +random-integer ()
+# +{
+# +    local -i bound=${1:-65536}
+# +
+# +    local -i bytes=2
+# +
+# +    # Max value of `od' statement is 65535, so `bc' computes a
+# +    # value less than $bound truncated (i.e., rounded down) to an
+# +    # integer.
+# +    bc <<< "scale=0; $(od -An -l -N$bytes /dev/urandom) * $bound / 65536"
+# +}
+# +
+# +# Return string of uniformly distributed random printable-ASCII chars.
+# +# If length is not specified, it defaults to 64.
+# +random-string ()
+# +{
+# +    local -i len=${1:-64}
+# +
+# +    local -a ascii_chars=( {0..9} {a..z} {A..Z} \! \# \$ % \& \( \) \* + - / \< = \> @ \[ \] ^ _ \{ \| \} \~ )
+# +    local -i char_count=${#ascii_chars[*]}
+# +    local id
+# +
+# +    for i in $(seq $len); do
+# +        id+="${ascii_chars[$(random-integer $char_count)]}"
+# +    done
+# +    printf "%s\n" "$id"
+# +}
+# +
+# +init-step-ca ()
+# +{
+# +    local -n argv=$1
+# +
+# +    if test -f "${argv[password_file]}"; then
+# +        echo "${argv[password_file]}: File exists; Cannot overwrite"
+# +    else
+# +        install -d -m 0700 "${argv[password_file]%/*}"
+# +        install -m 0600 <(random-string) "${argv[password_file]}"
+# +    fi
+# +
+# +    if test -f "${argv[provisioner_password_file]}"; then
+# +        echo "${argv[provisioner_password_file]}: File exists; Cannot overwrite"
+# +    else
+# +        install -d -m 0700 "${argv[provisioner_password_file]%/*}"
+# +        install -m 0600 <(random-string) "${argv[provisioner_password_file]}"
+# +    fi
+# +
+# +    step ca init \
+# +         --name "${argv[name]}" \
+# +         --provisioner "${argv[provisioner]}" \
+# +         --dns "${argv[fqdn]}" \
+# +         --address "${argv[address]}" \
+# +         --password-file "${argv[password_file]}" \
+# +         --provisioner-password-file "${argv[provisioner_password_file]}"
+# +
+# +    # Update $(step path)/config/ca.json to:
+# +    #
+# +    #    "db": {
+# +    #       "type": "badgerV2",
+# +    #       "dataSource": "/root/.step/db",
+# +    #       "badgerFileLoadingMode": "FileIO"
+# +    #    }
+# +    #
+# +    # See: https://github.com/smallstep/certificates/issues/279#issuecomment-635686362
+# +    #
+# +    local data_source=$(jq '.db.dataSource' < "$(step path)/config/ca.json")
+# +
+# +    local tmpfile=$(mktemp "/tmp/${FUNCNAME[0]}.XXXXX")
+# +
+# +    trap 'rm -rf "$tmpfile"; exit' 0 1 2 15
+# +
+# +    jq '.db = { "type" : "badgerV2", "dataSource" : '"$data_source"', "badgerFileLoadingMode" : "FileIO" }' < "$(step path)/config/ca.json" >"$tmpfile"
+# +
+# +    mv "$(step path)/config/ca.json"{,~}
+# +    install -m 0644 "$tmpfile" "$(step path)/config/ca.json"
+# +
+# +    rm -f "$tmpfile"
+# +    trap - 0 1 2 15
+# +}
+# +
+# +if test ."$0" = ."${BASH_SOURCE[0]}"; then
+# +    declare -A param=(
+# +        [name]="@NAME@"
+# +        [provisioner]="@PROVISIONER@"
+# +        [fqdn]="@FQDN@"
+# +        [address]="@ADDRESS@"
+# +        [password_file]="@PASSWORD_FILE@"
+# +        [provisioner_password_file]="@PROVISIONER_PASSWORD_FILE@"
+# +    )
+# +
+# +    init-step-ca 'param'
+# +fi
