REVO i.MX7D: Consolidate Debian and Ubuntu build environments.

diff --git a/contrib/OCI/build-builder-image b/contrib/OCI/build-builder-image
--- a/contrib/OCI/build-builder-image
+++ b/contrib/OCI/build-builder-image
@@ -9,6 +9,7 @@
 : ${CAT:='/bin/cat'}
 : ${CHMOD:='/bin/chmod'}
 : ${CHROOT:='/usr/sbin/chroot'}
+: ${CP:='/bin/cp'}
 : ${DF:='/bin/df'}
 : ${FINDMNT:='/bin/findmnt'}
 : ${GIT:='/usr/bin/git'}
@@ -18,20 +19,28 @@
 : ${JQ:='/usr/bin/jq'}
 : ${MKDIR:='/bin/mkdir'}
 : ${MOUNT:='/bin/mount'}
+: ${MV:='/bin/mv'}
 : ${NMCLI:='/usr/bin/nmcli'}
 : ${PODMAN:='/usr/bin/podman'}
 : ${READLINK:='/bin/readlink'}
 : ${RM:='/bin/rm'}
 : ${SED:='/bin/sed'}
+: ${SLEEP:='/bin/sleep'}
 : ${SOPS:="${HOME}/.asdf/shims/sops"}
 : ${SUDO:='/usr/bin/sudo'}
 : ${SYSTEMCTL:='/bin/systemctl'}
 : ${TAR:='/bin/tar'}
 : ${TEE:='/usr/bin/tee'}
+: ${TOUCH:='/bin/touch'}
 : ${UMOUNT:='/bin/umount'}
 : ${ZFS:='/sbin/zfs'}
 
 pr-info ()
+{
+    printf "I: %s\n" "$@" >&2
+}
+
+pr-err ()
 {
     printf "I: %s\n" "$@" >&2
 }
@@ -69,10 +78,10 @@ enable-qemu-arm ()
     local qemu_arm=/proc/sys/fs/binfmt_misc/qemu-arm
 
     if ! $SUDO $SYSTEMCTL enable --now binfmt-support &>/dev/null; then
-        pr-info "${script_name}: binfmt-support not available"
+        pr-err "${script_name}: binfmt-support not available"
         return 1
     elif test ! -f "$qemu_arm" -o ."$($HEAD -1 $qemu_arm)" != .'enabled'; then
-        pr-info "${script_name}: qemu-arm: QEMU ARM interpreter not available"
+        pr-err "${script_name}: qemu-arm: QEMU ARM interpreter not available"
         return 2
     fi
 }
@@ -143,18 +152,34 @@ build-builder ()
 
     if test ."$old_image" != .''; then
         pr-info "Removing old container image: localhost/${name}"
-
         $SUDO $BUILDAH rmi "$old_image" &>/dev/null || true
     fi
 
     if ! $SUDO $BUILDAH images "localhost/${name}" &>/dev/null; then
-
         pr-info "Pulling container image: ${image}:${tag}"
 
-        local container=$($SUDO $BUILDAH from "${image}:${tag}")
-        local mount_point=$($SUDO $BUILDAH mount "$container")
+        local container
+        local mount_point
 
-        $SUDO $TEE $mount_point/install_prerequisites >/dev/null <<EOF
+        container=$($SUDO $BUILDAH from "${image}:${tag}") || return $?
+        mount_point=$($SUDO $BUILDAH mount "$container") || return $?
+
+        if test -f "${mount_point}/etc/hosts"; then
+            $SUDO $CP -a "${mount_point}/etc/hosts"{,~}
+        else
+            $SUDO $TOUCH  "${mount_point}/etc/hosts~"
+        fi
+
+        if test -f "${mount_point}/etc/resolv.conf"; then
+            $SUDO $CP -a "${mount_point}/etc/resolv.conf"{,~}
+        else
+            $SUDO $TOUCH  "${mount_point}/etc/resolv.conf~"
+        fi
+
+        $SUDO $INSTALL -m 0644 /etc/hosts "${mount_point}/etc"
+        $SUDO $INSTALL -m 0644 /etc/resolv.conf "${mount_point}/etc"
+
+        $SUDO $TEE "${mount_point}/install_prerequisites" >/dev/null <<EOF
 #!/bin/bash
 #
 # @(#) install_prerequisites
@@ -162,7 +187,7 @@ build-builder ()
 : \${HOST_GW_IPV4:=$(get-external-ip)}
 EOF
 
-        $SUDO $TEE -a $mount_point/install_prerequisites >/dev/null <<'EOS'
+        $SUDO $TEE -a "${mount_point}/install_prerequisites" >/dev/null <<'EOS'
 
 install-prerequisites ()
 {
@@ -186,16 +211,14 @@ EOF
         cat >"$proxy" <<EOF
 Acquire::http::Proxy "http://${HOST_GW_IPV4}:3142";
 EOF
-    else
-        DEBIAN_PROXY=''
     fi
 
-    apt -qy install autoconf automake autopoint bc binfmt-support \
-        binutils bison build-essential cmake coreutils debootstrap \
-        device-tree-compiler ed flex g++ gcc git golang gpg groff gzip \
-        help2man kmod libncurses-dev libssl-dev libtool lzop m4 make \
-        parted qemu qemu-user-static rsync sudo u-boot-tools unzip \
-        upx-ucl
+    DEBIAN_FRONTEND=noninteractive apt -qy install autoconf automake          \
+        autopoint bc binfmt-support binutils bison build-essential            \
+        cmake coreutils debootstrap device-tree-compiler ed flex g++          \
+        gcc git golang gpg groff gzip help2man kmod libncurses-dev            \
+        libssl-dev libtool lzop m4 make parted qemu qemu-user-static          \
+        rsync sudo u-boot-tools unzip upx-ucl
 
     apt -qy install binutils-arm-linux-gnueabihf
     apt -qy install cpp-arm-linux-gnueabihf
@@ -218,7 +241,7 @@ EOF
 install-prerequisites
 EOS
 
-        $SUDO $CHMOD 0755 "$mount_point/install_prerequisites"
+        $SUDO $CHMOD 0755 "$mount_point/install_prerequisites" || return $?
 
         trap 'umount-fs "$mount_point"; exit' 0 1 2 15
 
@@ -227,7 +250,8 @@ EOS
         pr-info "Installing builder prerequisites..."
 
         $SUDO $CHROOT "$mount_point" ./install_prerequisites >&2
-        $SUDO $RM -f $mount_point/install_prerequisites
+        $SUDO $RM -f "${mount_point}/install_prerequisites"
+
         umount-fs "$mount_point"
 
         trap - 0 1 2 15
@@ -257,45 +281,12 @@ EOS
              --label name="$name" "$container" >&2
         $SUDO $BUILDAH commit "$container" "$name" >&2
         $SUDO sync
+        $SLEEP 5
         $SUDO $BUILDAH rm "$container" >&2
     fi
 
     $SUDO $BUILDAH inspect "localhost/${name}" |
         $JQ -r '.FromImageID'
-}
-
-create-external-volume ()
-{
-    local output_dir=$1
-    local volume_name=$2
-    # local external_src=$3
-    # local root_filesystem=$4
-    # local recovery_filesystem=$5
-    # local kernel_version=$6
-
-    local dest_dir=${output_dir}/${volume_name}
-
-    pr-info "Populating external volume..."
-
-    local fs_mount=$($SUDO $DF "$output_dir" | $AWK 'NR > 1 { print $NF }')
-    local fs_type=$($SUDO $FINDMNT -n "$fs_mount" | $AWK '{ print $3 }')
-
-    if test ."$fs_type"  = .'zfs'; then
-        local filesystem=$($SUDO $DF "$output_dir" | $AWK 'NR > 1 { print $1 }')
-
-        if ! $SUDO $ZFS create -p -o mountpoint="${dest_dir}" \
-             "${filesystem}/${volume_name}"; then
-            pr-info "${script_name}: ${dest_dir}: Cannot create directory"
-            return 1
-        fi
-    else
-        if ! $SUDO $INSTALL -d "${dest_dir}"; then
-            pr-info "${script_name}: ${dest_dir}: Cannot create directory"
-            return 2
-        fi
-    fi
-
-    echo "$dest_dir"
 }
 
 reset-window-title ()
@@ -306,40 +297,35 @@ reset-window-title ()
 if test ."$0" = ."${BASH_SOURCE[0]}"; then
     declare script=$(readlink -e "$0")
     declare machine=${1:-'revo-roadrunner-mx7'}
+    declare distribution=${2:-'debian'}
+
 
     declare script_name=${script##*/}
     declare script_dir=${script%/*}
     declare vendor_path=${script_dir}/../../revo
     # declare external_src=${script_dir}/../../src
 
-    # Look in ${machine}.conf for missing variable definitions...
-    load-configuration "${vendor_path}/${machine}/${machine}.conf"
-    enable-qemu-arm || exit 1
+    # Load  variable definitions from ${machine}-${distribution}.conf.
+    load-configuration "${vendor_path}/${machine}/${machine}-${distribution}.conf"
+    enable-qemu-arm || exit $?
 
-    declare builder_id=$(
+    declare builder_id
+
+    builder_id=$(
         build-builder "$builder_image" "$builder_tag" "$builder_name" \
                       "$build_script" "$kernel_version"
-            )
+              ) || exit $?
 
     if test ."$builder_id" = .''; then
-        pr-info "${script_name}: Cannot build builder image"
+        pr-err "${script_name}: Cannot build builder image"
         exit 2
     else
         pr-info "builder_id: $builder_id"
     fi
 
-    declare volume_name=roadrunner-${kernel_version}_$(date -u +%Y%m%dT%H%M%SZ)
-    # declare dest_dir=$(
-    #     create-external-volume "$output_dir" "$volume_name" \
-    #                            "$external_src" "$root_filesystem" \
-    #                            "$recovery_filesystem" "$kernel_version"
-    #         )
-    declare dest_dir=$(create-external-volume "$output_dir" "$volume_name")
-
-
     $CAT >&2 <<EOF
 ════════════════════════════════════════════════════════════════════════════════
-Builder container image: ${builder_name}
+Builder image: ${builder_name}
 Derived from: ${builder_image}:${builder_tag}
 Destination: ${dest_dir}
 ────────────────────────────────────────────────────────────────────────────────
