REVO i.MX7D: Add error handling to container scripts.

diff --git a/contrib/OCI/container-build-release b/contrib/OCI/container-build-release
--- a/contrib/OCI/container-build-release
+++ b/contrib/OCI/container-build-release
@@ -2,13 +2,17 @@
 #
 # @(#) container-build-release
 #
-# Copyright © 2021, 2022 Revolution Robotics, Inc.
+# Copyright © 2021-2023 Revolution Robotics, Inc.
 #
-declare script=$(readlink -e "$0")
-declare script_dir=${script%/*}
-declare script_name=${script##*/}
-
-source "${script_dir}/build-builder-image"
+: ${AWK_CMD:='/usr/bin/gawk'}
+: ${CAT_CMD:='/bin/cat'}
+: ${DF_CMD:='/bin/df'}
+: ${FINDMNT_CMD:='/bin/findmnt'}
+: ${INSTALL_CMD:='/usr/bin/install'}
+: ${PODMAN_CMD:='/usr/bin/podman'}
+: ${READLINK_CMD:='/bin/readlink'}
+: ${SUDO_CMD:='/usr/bin/sudo'}
+: ${ZFS_CMD:='/sbin/zfs'}
 
 create-external-volume ()
 {
@@ -19,20 +23,35 @@ create-external-volume ()
 
     pr-info "Populating external volume..."
 
-    local fs_mount=$($DF "$output_dir" | $AWK 'NR > 1 { print $NF }')
-    local fs_type=$($FINDMNT -n "$fs_mount" | $AWK '{ print $3 }')
+    local fs_mount=''
+    local fs_type=''
+
+    fs_mount=$(
+        $DF_CMD "$output_dir" |
+            $AWK_CMD 'NR > 1 { print $NF }'
+            ) || return $?
+    fs_type=$(
+        $FINDMNT_CMD -n "$fs_mount" |
+            $AWK_CMD '{ print $3 }'
+           ) || return $?
 
     if test ."$fs_type"  = .'zfs'; then
-        local dataset=$($DF "$output_dir" | $AWK 'NR > 1 { print $1 }')
+        local dataset=''
 
-        if ! $SUDO $ZFS create -p -o mountpoint="${dest_dir}" \
+        dataset=$(
+            $DF_CMD "$output_dir" |
+                $AWK_CMD 'NR > 1 { print $1 }'
+               ) || return $?
+
+
+        if ! $SUDO_CMD $ZFS_CMD create -p -o mountpoint="${dest_dir}" \
              "${dataset}/${volume_name}"; then
-            pr-err "${script_name}: ${dest_dir}: Cannot create directory"
+            pr-err "${FUNCNAME[0]}: ${dest_dir}: Cannot create directory"
             return 1
         fi
     else
-        if ! $SUDO $INSTALL -d "${dest_dir}"; then
-            pr-err "${script_name}: ${dest_dir}: Cannot create directory"
+        if ! $SUDO_CMD $INSTALL_CMD -d "${dest_dir}"; then
+            pr-err "${FUNCNAME[0]}: ${dest_dir}: Cannot create directory"
             return 2
         fi
     fi
@@ -51,7 +70,7 @@ run-builder ()
 
         pr-info "Running with:  apparmor=unconfined"
 
-        $SUDO $PODMAN run -it --rm --privileged \
+        $SUDO_CMD $PODMAN_CMD run -it --rm --privileged \
              --security-opt apparmor=unconfined \
              -v "${dest_dir}:${build_dir}:rshared,rbind,exec,dev,suid,rw" \
              "$builder_id"
@@ -59,45 +78,53 @@ run-builder ()
 
         pr-info "Running with:  privilege"
 
-        $SUDO $PODMAN run -it --rm --privileged \
+        $SUDO_CMD $PODMAN_CMD run -it --rm --privileged \
                -v "${dest_dir}:${build_dir}:rshared,rbind,exec,dev,suid,rw" \
                "$builder_id"
     fi
 
-    # $SUDO $PODMAN rmi "$builder_id" &>/dev/null
+    # $SUDO_CMD $PODMAN_CMD rmi "$builder_id" &>/dev/null
 }
 
 if test ."$0" = ."${BASH_SOURCE[0]}"; then
+    declare script=$($READLINK_CMD -e "$0")
+    declare script_dir=${script%/*}
+    declare script_name=${script##*/}
+
+    source "${script_dir}/build-builder-image"
+
     declare client=${1:-'UD'}
     declare distribution=${2:-'debian'}
     declare machine=${3-'revo-roadrunner-mx7'}
 
     declare vendor_path=${script_dir}/../../revo
 
-    # Load  variable definitions from ${machine}-${distribution}.conf.
-    load-configuration "${vendor_path}/${machine}/${machine}-${distribution}.conf"
-    enable-qemu-arm || exit $?
+    trap 'reset-window-title; exit 1' 0 1 2 15
 
-    declare builder_id
+    # Load  variable definitions from ${machine}-${distribution}.conf.
+    load-configuration "${vendor_path}/${machine}/${machine}-${distribution}.conf" || exit $?
+
+    declare builder_id=''
 
     builder_id=$(
         build-builder "$builder_name" "$builder_image" "$builder_tag" \
                       "$build_script" "$client"
-            ) || exit $?
+              ) || exit $?
 
     if test ."$builder_id" = .''; then
         pr-err "${script_name}: Cannot build builder image"
-        exit 2
+        exit 3
     else
         pr-info "builder_id: $builder_id"
     fi
 
-    declare volume_name=roadrunner-${kernel_version}_$(date -u +%Y%m%dT%H%M%SZ)
+    declare volume_name=''
+    declare dest_dir=''
 
-    declare dest_dir=$(create-external-volume "$output_dir" "$volume_name")
+    volume_name=roadrunner-${kernel_version}_$(date -u +%Y%m%dT%H%M%SZ) || exit $?
+    dest_dir=$(create-external-volume "$output_dir" "$volume_name") || exit $?
 
-
-    $CAT >&2 <<EOF
+    $CAT_CMD >&2 <<EOF
 ════════════════════════════════════════════════════════════════════════════════
 Client: ${client}
 Builder image: ${builder_name}
@@ -107,6 +134,9 @@ Destination: ${dest_dir}
 EOF
     read -p 'Press any key to continue...'
 
-    run-builder "$builder_id" "$dest_dir" "$build_dir"
+    run-builder "$builder_id" "$dest_dir" "$build_dir" || exit 4
+
     reset-window-title
+
+    trap - 0 1 2 15
 fi
